# Generated by Django 6.0.1 on 2026-02-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='news/images/')),
                ('tags', models.CharField(default='CELEBRATION', help_text='Comma-separated tags', max_length=255)),
                ('excerpt', models.TextField(help_text='Short summary for the homepage')),
                ('content', models.TextField(blank=True, help_text='Full article content (optional for now)')),
                ('published_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
