# Generated by Django 6.0.1 on 2026-02-06 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('store', '0003_product_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Link a product to allow ordering from this news post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
