# Generated by Django 6.0.1 on 2026-02-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_date_order_fulfillment_method_and_more'),
        ('store', '0002_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='addons',
            field=models.ManyToManyField(blank=True, to='store.addon'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_message',
            field=models.TextField(blank=True),
        ),
    ]
